# Generated by Django 3.2.6 on 2021-08-16 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Messages', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='Unread',
            new_name='unread',
        ),
    ]
