# Generated by Django 3.2.6 on 2021-08-17 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Messages', '0002_rename_unread_message_unread'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='creation_data',
            new_name='created_date',
        ),
    ]
